version: '3.7'

services:
  client:
    container_name: 'ecommerce-vuejs3-typescript_client'
    build: ./docker/client
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev']

  server:
    container_name: 'ecommerce-vuejs3-typescript_server'
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3001 -w endpoint.json
    ports:
      - "3001:3001"
    volumes:
      - ./api:/data
    restart: always